
spring: 
  mvc:
    view: # JSP 사용 설정
      prefix: /WEB-INF/view/ # jsp 파일 경로
      suffix: .jsp # 확장자
  datasource: # DB 설정 (MYSQL으로 마이그레이션하기) ***
    url: jdbc:mysql://localhost:3306/apiTest?serverTimezone=Asia/Seoul # bank2는 DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 유저 이름
    password: asd1234 # 비밀번호 (비워두면 비밀번호 X)
    
mybatis:
  mapper-locations:         # **.xml : 해당 경로 아래 모든 xml 파일
  - classpath:mapper/**.xml # classpath는 src/main/resources/ 아래부터 시작
  configuration:
    map-underscore-to-camel-case: false